
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ButtonGroup from '@/app/button-group'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Next를 위한 연습",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full h-[100px] bg-red-300'>
          <ButtonGroup />
        </div>
        {children}
      </body>
    </html>
  );
}
