"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Next를 위한 연습",
  description: "Generated by create next app",
};

function Button({children, onClick}){
  return (
    <div
      className='border-2 border-solid p-[10px] border-white inline-block'
      onClick={onClick}
    >
      {children}
    </div>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const router = useRouter()
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className='w-full h-[100px] bg-red-300 flex-row'>
            <Button onClick={() => router.back()}>뒤로 가기</Button>
            <Button onClick={() => router.refresh()}>새로고침</Button>
            <Button onClick={() => router.forward()}>앞으로 가기</Button>
            
        </div>
        {children}
      </body>
    </html>
  );
}
